### ISSUE TITLE
Security of plists, consider recommending programmatic approach

### ISSUE THREAD

**Issue by StupidDutchName** [datatheorem/TrustKit#102]
Currently your project recommends to set configuration in the `Info.plist` of a project. You have implemented a programmatic configuration for TrustKit though (kudo's!). It's trivally easy for a hacker/script kiddie on a compromised device to change the Info.plist, and thus the TrustKit configuration. Reverse engineering and changing the binary is also possible, but requires a much higher skill level hacker.

Please consider encouraging users to use the programmatic configuration (and make the Info.plist the alternative) or mention at the programmatic configuration that you might want to do this if you want to implement it more securely.

**Comment by nabla-c0d3** [comment]
Hello and thanks for the feedback!
I respectfully disagree tho: a compromised App/device is not part of SSL pinning's thread model. SSL pinning adds security against network attacks; the fact that it makes reverse-engineering an App sightly harder is merely a side-effect, but not the goal.

There's plenty of tools available to disable pinning even when initialized programmatically ( such as my own: https://github.com/nabla-c0d3/ssl-kill-switch2 ) so it doesn't really make it that much harder. 

Overall if you want to make your App very hard to reverse-engineer, you will have to write your own, heavily-obfuscated and custom SSL pinning implementation; leveraging a widely used pinning library will not work for this. I would advise against this tho as I personally don't see researchers reverse-engineering an App as a big security threat (it has more to do with IP protection and DRMs).
Hope this makes sense!
