### ISSUE TITLE
Add the configured TSKAlgorithms to pinning reports

### ISSUE THREAD

**Issue by nabla-c0d3** [datatheorem/TrustKit#105]
Setting the wrong algorithm in a pinning policy will result in pinning failures. However, the corresponding reports do not have the selected algorithm in them, making it hard to troubleshoot and understand the pinning failure on the reporting server.

**Comment by adamkaplan** [comment]
Does this still apply given #111?

**Comment by nabla-c0d3** [comment]
I think so, because #111 will only be implemented once we drop support for iOS 9.

**Comment by nabla-c0d3** [comment]
We're now not that far from implementing #111 so this no longer applies.
