### ISSUE TITLE
Support for SHA1 signature algorithm

### ISSUE THREAD

**Issue by sriharsha-y** [datatheorem/TrustKit#107]
I could not find proper provision where i can specify the signature algorithm to be used. I suppose It is by default using the SHA256 signature algorithm. I could not even find any samples on using SHA1 in TrustKit. Am i missing something ?

will be thankful if i can get any sample on using SHA1.

**Comment by nabla-c0d3** [comment]
If you are talking about the format of the SSL pins, it is SHA 256. We do not support SHA 1 as the pin format is a standard described in https://tools.ietf.org/html/rfc7469.
