### ISSUE TITLE
How about the safety of Info.plist.

### ISSUE THREAD

**Issue by internalG** [datatheorem/TrustKit#108]
The easy way to use your library is to save the hashes in the plist file. So if someone gets the .ipa and plist, can he harm the security of client and server? Thanks.

**Comment by nabla-c0d3** [comment]
Hello,

If an attacker is able to change the content of the plist in the IPA file on someone else's device (or is able to get the other person to install a modified IPA), then any security mechanism in the App (pinning and other) can be disabled. 
Even when not using the plist approach, the attacker could for example modify the binary itself to inject code and disable TrustKit (see https://github.com/nabla-c0d3/ssl-kill-switch2) and/or repackage the IPA and do many other things that completely compromise all security within the App (not just pinning). Full access to the plist file is the same as being able to inject code in the App.

Overall, this is why a compromised App/device is not part of SSL pinning's thread model (or any client-side security mechanism for that matter).

**Comment by dlow-yahoo-inc** [comment]
The hashes in the .plist are hashes of public keys. As such, they can be "publicly" accessible without negatively impacting the security model. The most they reveal would be what root CA provided your TLS certificates (also public information).

As @nabla-c0d3 described, attackers can obviously repackage the IPA and try to edit or disable pinning via the .plist (or hex editing your app binary). But that attack vector exists with or without TrustKit and is not what certificate pinning is meant to solve.

**Comment by internalG** [comment]
@nabla-c0d3 you wrote ssl-kill-switch2! Bad bad boy😎
