### ISSUE TITLE
Deprecate TSKPublicKeyAlgorithms after dropping support for iOS 9

### ISSUE THREAD

**Issue by nabla-c0d3** [datatheorem/TrustKit#111]
In iOS 10, it is possible to identify the type of public key using `SecKeyCopyAttributes()`, thereby removing the need for the developer to specify the key algorithm in the TrustKit policy.

**Comment by nabla-c0d3** [comment]
We would only enable this once we drop support for iOS 9, so that we don't have two different validation code paths (which may return different results) based on the device's iOS version.

**Comment by edwardmp** [comment]
@nabla-c0d3 With iOS 12 around the corner, hasn't the time arrived to drop iOS 9 support?

**Comment by nabla-c0d3** [comment]
Agreed - we'll remove iOS 9 support in the next release.

**Comment by edwardmp** [comment]
@nabla-c0d3 
Great. Anything I can do to help remove iOS 9 support? I guess it mostly resolves around removing iOS 9 specific code?

**Comment by nabla-c0d3** [comment]
Thanks - I will take care of it tho as I know exactly what needs to be done.

**Comment by edwardmp** [comment]
Thanks great job. Will test this in a current beta project.

By the way, there's still a iOS 8 reference present in the readme (first paragraph) ;)

**Comment by nabla-c0d3** [comment]
Released with v1.6.0.
