### ISSUE TITLE
TrustKit: Successfully initialized with configuration for wrong keys

### ISSUE THREAD

**Issue by devalchauhan** [datatheorem/TrustKit#117]
<img width="865" alt="screenshot 2017-06-18 12 16 38" src="https://user-images.githubusercontent.com/1390592/27259279-0497f05c-5420-11e7-87aa-3469c636ec2c.png">

static let PINNING_HASH_1 : String = "afwiKY4RxoMmLkuRW1l7QsPZTJPwDS2pdDROQjXw8ig="
static let PINNING_HASH_2 : String = "klO23nT3ehFDXCfx3eHTDRESMz3asj1muO+4aIdjiuY="
static let PINNING_HASH_3 : String = "grX4Ta4HpZx6tSHkmCrvpApTQGo67CYDnvprLg5yRME="

I have tried to connect yahoo.com using this wrong key, and my server eservices.dha.gov.ae using same false public key, and this configuration always returns success :(  and never check for valid public key, while call happens from iOS application using URLSession.
I am not sure what is wrong could you please guide me, please guide me i am working on swift language

**Comment by nabla-c0d3** [comment]
Please make sure that the authentication handler code in your network delegate is like this: https://datatheorem.github.io/TrustKit/documentation/Classes/TSKPinningValidator.html#/c:objc(cs)TSKPinningValidator(cm)handleChallenge:completionHandler:
