### ISSUE TITLE
Final API for 1.5.0

### ISSUE THREAD

**Issue by nabla-c0d3** [datatheorem/TrustKit#124]
On the current branch for 1.5.0 ( https://github.com/datatheorem/TrustKit/blob/alban-review/TrustKit/TrustKit.h#L121 ), the main `TrustKit` class has the following API:

```
#pragma mark Usage in Singleton Mode

+ (void)initializeWithConfiguration:(NSDictionary<TSKGlobalConfigurationKey, id> *)trustKitConfig;
+ (instancetype)sharedInstance;


#pragma mark Implementing Pinning Validation

@property (nonatomic, nonnull) TSKPinningValidator *pinningValidator;


#pragma mark Configuring a Validation Callback

@property (nonatomic, nullable) TSKPinningValidatorCallback pinningValidatorCallback;
@property (nonatomic, null_resettable) dispatch_queue_t pinningValidatorCallbackQueue;

#pragma mark Usage in Multi-Instance Mode

- (instancetype)initWithConfiguration:(NSDictionary<TSKGlobalConfigurationKey, id> *)trustKitConfig;

#pragma mark Other Settings

+ (void)setLoggerBlock:(void (^)(NSString *))block;
```

The way the two constructors are named and work feels a bit inconsistent and not really like what an Objective-C / Swift API should look like. It might be better to go back to a settable property for the configuration? Especially if we decide to eventually allow changing the configuration ( #123 ).

Also `+ setLoggerBlock` it  not great since it modifies logging for all instances (not just the shared instance), but we might have to keep it for now as fixing the implementation is a larger project.

Overall, what would be the "right" API to expose here? Pinging @adamkaplan @dlow-yahoo-inc .

**Comment by novixon** [comment]
@nabla-c0d3 Now I am a bit confused :) Did you said it is impossible (or very hard) to clean the TLS cache? So how the reconfiguration of TristKit can be done?

Also, let me suggest an extension of TrustKit public API. It will be useful to have methods like "hashSubjectPublicKeyInfoFromCertificate" in the API. For example if you want to compare pins without doing any other SSL Pinning stuff.
