### ISSUE TITLE
TSKDisableDefaultReportUri disabled, despite being enabled in the configuration

### ISSUE THREAD

**Issue by acecilia** [datatheorem/TrustKit#125]
Hello:

I realised that despite setting kTSKDisableDefaultReportUri to true, my app was sending the reports to the default URI. After checking the configuration I got the following:

<img width="827" alt="screen shot 2017-07-06 at 18 42 46" src="https://user-images.githubusercontent.com/7938671/27922380-23360b20-627b-11e7-9576-84b812385f4d.png">

So seems that, despite being enabled in the configuration, TSKDisableDefaultReportUri is not enabled.
Am I doing something wrong or is this a bug?

This is TrustKit 1.4.2 running in an iPhone5S with iOS 10.3.1.
Thanks!

**Comment by nabla-c0d3** [comment]
Hello, 
`kTSKDisableDefaultReportUri` is a per-domain configuration key. Hence it should be put inside your `kTSKPinnedDomains` dictionary, in each domain entry.
