### ISSUE TITLE
Files missing in the TrustKit_Static target

### ISSUE THREAD

**Issue by boundsj** [datatheorem/TrustKit#131]
Thanks for the library and the great changes in the new release!

In the [1.5.0](https://github.com/datatheorem/TrustKit/releases/tag/1.5.0) release, `TSKPinningValidatorResult.m` and `TSKSPKIHashCache.m` are not included in the `TrustKit_Static` target. This causes a build failure when using the `Embedding TrustKit Without CocoaPods` approach that had its description removed in https://github.com/datatheorem/TrustKit/commit/e61d7d053fa4af82e5789be2a7b13d31fc9f6821

Also, it'd be great if breaking API changes like the ones in 1.5.0 were introduced in a major version bump for clarity.

**Comment by nabla-c0d3** [comment]
It has been released as part of v1.5.1.
