### ISSUE TITLE
kTSKValidationCompletedNotification missing in 1.5.0

### ISSUE THREAD

**Issue by klaaspieter** [datatheorem/TrustKit#135]
It appears the `kTSKValidationCompletedNotification` is no longer defined in 1.5.0. Was it intentionally removed? Is `pinningValidatorCallback` the alternative? If so perhaps it can be added to the 1.5.0 release notes?

I've been using the notification to write to an error log when validations failed. A backend service then notifies us of the failure. I opted for this solution, as opposed to the built-in solution, because this was easier to get setup.

**Comment by nabla-c0d3** [comment]
Hello,
Yes, the callback replaces the notifications; it's mentioned in the release notes: 
> Pinning validation notifications have been removed and replaced by a callback that can be set in order to receive information about any pinning validation performed by TrustKit. See the pinningValidatorCallback property of the TrustKit class for more information.

**Comment by klaaspieter** [comment]
That's embarrassing. I read over those a couple of but didn't see any mention.

Either way: Closed 👍🏼
