### ISSUE TITLE
I am not able to build, public method is missing.

### ISSUE THREAD

**Issue by Krisiacik** [datatheorem/TrustKit#137]
I am using cocoapods, trying to pod 1.4.1, 1.4.2 and 1.5.0.

All those versions end up with this message.
![trustkiterror](https://user-images.githubusercontent.com/9870899/28628225-faf516dc-721b-11e7-8ab3-665c5d770b27.png)

Funny thing is code completion works.

**Comment by nabla-c0d3** [comment]
Hello, 
The `TSKPinningValidator` methods are class methods on 1.4.2- and an instance methods on 1.5.0+. Also the `configuration()` method was removed from 1.5.0.
