### ISSUE TITLE
Why TrustKit ignore TLDs in isSubdomain method?

### ISSUE THREAD

**Issue by allenhsu** [datatheorem/TrustKit#138]
https://github.com/datatheorem/TrustKit/blob/master/TrustKit/configuration_utils.m#L18

In the isSubdomain method, why does TrustKit only compare length of TLDs but not the entire string?

We encountered a bug that we only pinned `domain.com` in client configuration, but actually we have some APIs on another domain like `api.domain.net`, which is mainly for metrics and error reporting, so we didn't and are not going to pin `domain.net`. Now all the requests to `api.domain.net` is failed because TrustKit consider `api.domain.net` as subdomain of `domain.com` but actually pubkey of it is not in the configuration of `domain.com`.

**Comment by allenhsu** [comment]
In other words, why you consider TLDs with same length as same TLDs?

**Comment by allenhsu** [comment]
Why isn't `[subDomain hasSuffix:domain]` sufficient?

**Comment by nabla-c0d3** [comment]
Hello,
Thanks for the report; this was a bug (now fixed).

**Comment by nabla-c0d3** [comment]
It has been released as part of v1.5.1.
