### ISSUE TITLE
TrustKit initialised with wrong config?

### ISSUE THREAD

**Issue by tejasna** [datatheorem/TrustKit#139]
<img width="756" alt="screen shot 2017-08-02 at 3 02 56 pm" src="https://user-images.githubusercontent.com/13996295/28867426-bacf839e-7793-11e7-8a0c-3d5ab282014b.png">

But when initialised 
"google.com" =         {
            TSKDisableDefaultReportUri = 0;
            TSKEnforcePinning = 1;
            TSKIncludeSubdomains = 1;
            TSKPublicKeyAlgorithms =             (
                0
            );

Could the `TSKPublicKeyAlgorthims` value being 0 be a reason for the Auto-swizzling to stop working on my app? I'm currently using the `URLSession` with a `URLRequest` from the `Foundation` class to make my network requests. Also i'm chaining my request with RxSwift's `Reactive` wrapper.

**Comment by nabla-c0d3** [comment]
In the latest version, you have to explicitly enable swizzling using the `TSKSwizzleNetworkDelegates` key.

**Comment by tejasna** [comment]
<img width="455" alt="screen shot 2017-08-03 at 12 25 10 pm" src="https://user-images.githubusercontent.com/13996295/28909651-eedfa840-7846-11e7-9309-8cdcc1f0827a.png">

The key is enabled as well. Need to do anything in code explicitly?

**Comment by nabla-c0d3** [comment]
Then it should work without modifying the code; make you sure you are using the latest version (1.5.1). There is working example of it here : https://github.com/nabla-c0d3/trustkit-testapps/tree/master/TestSwizzling

**Comment by tejasna** [comment]
Looks like using the `shared` instance of the`URLSession` directly causes the Auto-swizzling to fail. Setting the `URLSessionDelegate` on the`URLSession` and then using it fixed the issue!
