### ISSUE TITLE
Add support for Swift

### ISSUE THREAD

**Issue by nabla-c0d3** [datatheorem/TrustKit#14]

**Comment by nabla-c0d3** [comment]
The current version actually works fine in Swift Apps; here's sample initialization code:

        var config = [
            "yahoo.com": [
                kTSKPublicKeyAlgorithms: [kTSKAlgorithmRsa2048],
                kTSKPublicKeyHashes: [
                    "JbQbUG5JMJUoI6brnx0x3vZF6jilxsapbXGVfjhN8Fg=",
                    "WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="
                    ],
                kTSKIncludeSubdomains: true,
                kTSKEnforcePinning: true,
                ]
            ]
        
        TrustKit.initializeWithConfiguration(config)

**Comment by Rahul379** [comment]
Hi
TrustKit.initializeWithConfiguration(config) is giving error. Can you help what is missing.

**Comment by ChristopherJoonMiller** [comment]
@Rahul379 the console log should explain what the problem is. 

Try something like this:
```
        let trustKitConfig = [
            kTSKSwizzleNetworkDelegates: true,
            kTSKPinnedDomains: [
                "yahoo.com": [
                    kTSKPublicKeyAlgorithms: [kTSKAlgorithmRsa2048],
                    kTSKPublicKeyHashes: [
                        "xxxxx", // actual key
                        "yyyyy"  // need a backup here
                    ],
                    kTSKIncludeSubdomains: true,
                    kTSKEnforcePinning: true,
                ]
            ]
        ]
        TrustKit.initializeWithConfiguration(trustKitConfig)
```
