### ISSUE TITLE
Getting Started Doc - Image not Displayed

### ISSUE THREAD

**Issue by Chris-Perkins** [datatheorem/TrustKit#143]
This is simply a minor error in markdown.

On the line stating: `![](https://datatheorem.github.io/TrustKit/images/linking3_dynamic.png)`, you simply need to remove the spacing at the start of the line to cause the image to display. It appears that this line was tabbed, causing the Markdown format to paste it as plain text. Was this intentionally done?

Current display:
![](http://i.imgur.com/opkb6qU.png?raw=true)

**Comment by Chris-Perkins** [comment]
Also, under "Leveraging additional trust anchors", the word "Example" is spelled "Exmaple"

**Comment by nabla-c0d3** [comment]
It's fixed now. Thanks!
