### ISSUE TITLE
On iOS 11.1b Pin validation fails

### ISSUE THREAD

**Issue by njoylab** [datatheorem/TrustKit#146]
Hello,
I've noticed that from iOS 11.1 beta pinning always fails.
I'm not sure what Apple changed and I know it's a beta but I thought it's an important information to consider. I hope things would be fixed in the next beta.

Does anyone have the same issue?

**Comment by nabla-c0d3** [comment]
Hello,
Thanks for letting us know! Do you see anything in the logs?

**Comment by njoylab** [comment]
> === TrustKit: Proxy-ing NSURLConnectionDelegate: AFHTTPRequestOperation
> === TrustKit: Checking certificate with CN: Amazon Root CA 1
> === TrustKit: Subject Public Key Info hash was found in the cache
> === TrustKit: Testing SSL Pin <fbe30180 31f9586b cbf41727 e417b7d1 c45c2f47 f93be372 a17b96b5 0757d5a2>
>  === TrustKit: Checking certificate with CN: Amazon
>  === TrustKit: Subject Public Key Info hash was found in the cache
> === TrustKit: Testing SSL Pin <252333a8 e3abb723 93d6499a bbacca86 04faefa8 4681ccc3 e5531d44 cc896450>
> === TrustKit: Checking certificate with CN: *.<domain>
> === TrustKit: Subject Public Key Info hash was found in the cache
> === TrustKit: Testing SSL Pin <70f8beba 49a87d05 f5768df9 5e8a4665 caf331ec 41a1394c 4ab60d25 3be7255f>
> === TrustKit: Error: SSL Pin not found for <domain>
> === TrustKit: Pin validation failed for <domain>
> === TrustKit: Pin failure report for <domain> was not sent due to rate-limiting

Is there a way to have more logs?

**Comment by nabla-c0d3** [comment]
Are you sure that you set the right pins in your app? We haven't received any other reports about this problem so I will close it. Feel free to re-open if this is still an issue.
