### ISSUE TITLE
TrustKit is allowing all connections even when I change the cert hashes

### ISSUE THREAD

**Issue by einsteinx2** [datatheorem/TrustKit#153]
I have TrustKit implemented in my application, and am testing that it's correctly blocking incorrect certificates. However, when I change the cert hashes for a domain to those from a different CA (so they're valid hashes, but not for that domain), I see the delegate method called but it is allowing the connections to work. It doesn't seem to be blocking any connections. I also confirmed it was initializing using my configuration.

I've successfully used TrustKit before, so I'm not sure what has changed other than upgrading to the latest TrustKit code to get access to the additional certificate algorithm we needed. I'm running macOS High Sierra 10.13.1 if that makes any difference.

You can see my config here as the application is open source:
https://github.com/balancemymoney/balance-open/blob/task/cert-pinning/Balance/Shared/Data%20Model/Singleton/CertValidator.m

Note that in that commit, I'm using the correct hashes. But to test the reporting feature and to ensure it was working, I switched some of the hashes in the Exchange API Servers section to use the Let's Encrypt hashes, and TrustKit seems to be allowing the connections when it should be rejecting them.

Am I doing anything obviously wrong, or is this a bug?

**Comment by einsteinx2** [comment]
I started debugging, and when I break in -[TSKPinningValidator evaluateTrust:forHostname], the domainPinningPolicies property is nil, so it's returning TSKTrustDecisionDomainNotPinned even though the domain is pinned. So that appears to be the the problem. I'm going to continue debugging now.

**Comment by einsteinx2** [comment]
Weird, I broke in the TSKPinningValidator init method and it's definitely getting my configuation, and at that moment, I can po the property and it returns my config. So somehow it's being cleared...

**Comment by einsteinx2** [comment]
Figured it out. Implementation problem on my end. I was creating my own pinning validator and not using the shared one. Now it's evaluating correctly. Not a bug on your end, sorry.

**Comment by nabla-c0d3** [comment]
Sounds good!
