### ISSUE TITLE
Subdomain verification is broken

### ISSUE THREAD

**Issue by Benzoate** [datatheorem/TrustKit#156]
TrustKit can erroneously identify other domains as subdomains, and as a result can use the wrong configuration. 

I've tracked the issue to the `isSubdomain` function in `configuration_utils.m`, which is only checking that the domain names have the same ending.

Example:
2 configurations for `domain.com` and `test-domain.com`. Attempting to connect to `en.test-domain.com` will use the configuration for `domain.com`, rather than `test-domain.com`. Even worse is that `totallynotthesamedomain.com` will also identify as a subdomain of `domain.com`.

**Comment by nabla-c0d3** [comment]
Thanks for the report and good catch! We will release a new version with the fix some time this week.

**Comment by nabla-c0d3** [comment]
The fix was released as part of 1.5.3.

**Comment by Benzoate** [comment]
Thank you! 👍
