### ISSUE TITLE
Does TrustKit support pinning domains used in an SFSafariViewController?

### ISSUE THREAD

**Issue by jgale** [datatheorem/TrustKit#163]
I was originally going to report this as a bug, but upon further investigation it's probably more of a question.

I am using the [AppAuth](https://github.com/openid/AppAuth-iOS) library to implement OpenID Connect flow for authorization. All of this is done in a web browser flow from within the app. On iOS 10 it uses SFSafariViewController, and on iOS 11 it uses SFAuthenticationSession (which I think might use SFSafariViewController under the hood).

AppAuth does a series of requests to sso.mycompany.com within a SFSafariViewController, but none of the requests get pinned. I am using swizzling of network delegates, which I was hoping would work here.

Here's my config:

```
let trustKitConfig: [String: Any] = [kTSKSwizzleNetworkDelegates: true,
                                     kTSKPinnedDomains: ["api.mycompany.com": [kTSKIncludeSubdomains: false,
                                                                               kTSKEnforcePinning: true,
                                                                               kTSKPublicKeyAlgorithms: [kTSKAlgorithmRsa2048],
                                                                               kTSKPublicKeyHashes: [apiServerPublicKeyHash, backupKeyHash]],
                                                         "sso.mycompany.com": [kTSKIncludeSubdomains: false,
                                                                               kTSKEnforcePinning: true,
                                                                               kTSKPublicKeyAlgorithms: [kTSKAlgorithmRsa2048],
                                                                               kTSKPublicKeyHashes: [ssoServerPublicKeyHash, backupKeyHash]]]]

TrustKit.initSharedInstance(withConfiguration: trustKitConfig)
```

I tried a direct GET request to sso.solium.com via AFNetworking and it does get pinned, as expected.

I'm guessing there is probably no way to hook into the auth challenges there, and maybe SFSafariViewController is using different networking requests under the hood so they don't get affected by kTSKSwizzleNetworkDelegates?

Thank you!

**Comment by nabla-c0d3** [comment]
Hello,

You guessed right: there is no way to do any SSL pinning in `SFSafariViewController`, for two reasons:

* The `SFSafariViewController` class does not provide any API for customizing SSL validation and handling authentication challenges.
* When used, the `SFSafariViewController` is actually run in a separate process and the app's code has no access to it at all. Hence swizzling does not affect the `SFSafariViewController` as it only happens in the app's process.

Hope this clarifies...

**Comment by nabla-c0d3** [comment]
Lastly, the only way to do pinning in a webview is to use `WKWebView`.

**Comment by jgale** [comment]
Thanks for clarifying, I appreciate it!

**Comment by sattaman** [comment]
I've also been looking into this and found the following open issue. https://github.com/openid/AppAuth-iOS/issues/324 . I'm not an ios developer, but it looks like it may be possible to pin here?

**Comment by nabla-c0d3** [comment]
@sattaman It only allows pinning for non-SFSafariViewController connections.

**Comment by sumeetguha** [comment]
@nabla-c0d3: As of now can we consider it as there is not an option to pin the certificate through appAuth in iOS?
