### ISSUE TITLE
Cancel SSL Pinning for multiple requests using UIWebView

### ISSUE THREAD

**Issue by sureshreddis** [datatheorem/TrustKit#164]
In my project am using UIWebView for most of the screens, am using custom NSURLProtocol which intercepts all webView requests. I want to perform pinning only once for domain URL and for subsequent requests i donot need. Can you please provide the steps how to prevent Pinning validation for subsequent requests using NSURLProtocol.

**Comment by nabla-c0d3** [comment]
Hello,
You do not need to worry about this, iOS already has a caching mechanism for authentication challenges; it stores the result of an SSL validation for about 10 minutes per domain. Hence SSL pinning will not be done on every single request; you can validate that by verifying that the `TSKPinningValidator` only gets called on the first connection to a domain, not on the subsequent connections.
