### ISSUE TITLE
TrustKit with AFNetworking

### ISSUE THREAD

**Issue by mariaCP** [datatheorem/TrustKit#165]
Hello,
is it possible integrate TrustKit with AFNetworking? Any suggestion?
Thank you!

**Comment by nabla-c0d3** [comment]
Hello,
You will need to create a handler for authentication challenges that calls `-[TSKPinningValidator handleChallenge:completionHandler:]` (sample code here: https://datatheorem.github.io/TrustKit/documentation/Classes/TSKPinningValidator.html#/c:objc(cs)TSKPinningValidator(im)handleChallenge:completionHandler: ). 

Then you can set your handler in `AFURLSessionManager` using this method: http://cocoadocs.org/docsets/AFNetworking/3.1.0/Classes/AFURLSessionManager.html#//api/name/setTaskDidReceiveAuthenticationChallengeBlock: .

**Comment by lukaszgieraltowski** [comment]
Hi,
this should do the job:
```
  [manager setSessionDidReceiveAuthenticationChallengeBlock:^NSURLSessionAuthChallengeDisposition(NSURLSession * _Nonnull session, NSURLAuthenticationChallenge * _Nonnull challenge, NSURLCredential *__autoreleasing  _Nullable * _Nullable credential) {
        __block NSURLSessionAuthChallengeDisposition dispositionToReturn = NSURLSessionAuthChallengePerformDefaultHandling;
        if (![TrustKit.sharedInstance.pinningValidator handleChallenge:challenge completionHandler:^(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential * _Nullable credential) {
            dispositionToReturn = disposition;
        }]){
            return NSURLSessionAuthChallengePerformDefaultHandling;
        }
        return dispositionToReturn;
    }];
```
