### ISSUE TITLE
SSLPinning not performing on WebView Subsequent calls

### ISSUE THREAD

**Issue by sureshreddis** [datatheorem/TrustKit#167]
Hi,
My app has WebView which loads requests.I have a scenario where multiple requests are being triggered in sequence. Sometimes SSL Pinning is not happening between the requests. Is there some property do i need to enable or? I am using TrustKit 1.4.2 version.

**Comment by nabla-c0d3** [comment]
This is due to the TLS cache: https://developer.apple.com/library/content/qa/qa1727/_index.html
