### ISSUE TITLE
Accept self signed certificates

### ISSUE THREAD

**Issue by jbrodriguez** [datatheorem/TrustKit#17]
Hi, this looks like a very nice library. 

I'm trying to use it with self-signed certificates (CA, Intermediate CA and EE) in an iOS app.

I'm getting "NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813)"

Reading these few lines, make me think that you need certificates signed by an authority trusted by iOS.

> static OSStatus replaced_SSLHandshake(SSLContextRef context)
> {
>    OSStatus result = original_SSLHandshake(context);
>    if ((result == noErr) && (_isTrustKitInitialized))
>    {

Please confirm.

**Comment by nabla-c0d3** [comment]
Hi,
Yes, you do need certificate signed by a CA that is part of the iOS trust store. It does not have to be a "public" CA (Verisign, etc.) but for private CAs, the certificate chain has to be valid and the CA has to be added to the iOS store (manually or via a configuration profile). 
We thought about supporting self-signed certificates, but it makes the validation a lot more dangerous as you can no longer rely on the iOS API to build a path and return a "sanitized"/validated version of the certificate chain, while also checking for things like revocation.
What is your use case exactly ?

**Comment by jbrodriguez** [comment]
Thank you, Alban.

I was considering self-signed certificates for an api endpoint/ios app which I control.

I can't have users of the app import my private CA into the iOS trust store :)

I will have to go the way of a public CA and use my CA for development.

Thanks, I'll close the issue/question :)

**Comment by nabla-c0d3** [comment]
Sounds good and I honestly think it's better to use a public CA (even just for compatibility with browsers) :)
