### ISSUE TITLE
Can't pin to Amazon AWS API gateway subdomain: Invalid domain

### ISSUE THREAD

**Issue by edwardmp** [datatheorem/TrustKit#170]
Hi,

Thanks for developing this!

I ran into some trouble getting it to pin against a AWS API gateway subdomain:
'TrustKit was initialized with an invalid domain [my-id].execute-api.eu-central-1.amazonaws.com'

This subdomain does not appear on the public suffix list.. so why does this happen?

**Comment by nabla-c0d3** [comment]
We'll look into it.
Thanks!

**Comment by nabla-c0d3** [comment]
I've updated the public suffix list; can you let me know if it fixed your issue? If not, please post the TrustKit configuration you are using.
Thanks!

**Comment by nabla-c0d3** [comment]
Any update? Thanks!

**Comment by n00bm5st3r69** [comment]
@edwardmp were you able to successfully pin your AWS API gateway subdomain? My app is also crashing when pinning *.execute-api.ap-southeast-1.amazonaws.com

**Comment by roopepal** [comment]
@nabla-c0d3 Can you confirm if pinning such API Gateway subdomains including the ID should be possible? I am also facing the same "TrustKit was initialized with an invalid domain [id].execute-api.[region].amazonaws.com".

**Comment by nabla-c0d3** [comment]
Hello,
It is by design that TrustKit will not allow you to pin a domain that has a certificate that you don't own, such amazonaws.com. When the certificate for this domain gets rotated by AWS, your application will stop working without any way for it to recover besides pushing an update.

**Comment by roopepal** [comment]
@nabla-c0d3 Thanks for the quick reply, I see your point. However, as Amazon points out (e.g., on the [ACM best practices page](https://docs.aws.amazon.com/acm/latest/userguide/acm-bestpractices.html#best-practices-pinning)), pinning to all available Amazon root certificates should be a viable option. These certificates of course have a very long lifetime. Do I then understand correctly that TrustKit cannot support this option?

**Comment by edwardmp** [comment]
@roopepal  what I eventually did is just use a custom domain. That works fine with TrustKit ;)

**Comment by nabla-c0d3** [comment]
@roopepal correct, this will not work with TrustKit. However, a custom domain will work fine.
