### ISSUE TITLE
Doesn't seem to work with React Native?

### ISSUE THREAD

**Issue by apski** [datatheorem/TrustKit#177]
App crashes on launch. I've even added React Native to the TrustKitDemo project following these steps:
[https://facebook.github.io/react-native/docs/integration-with-existing-apps](https://facebook.github.io/react-native/docs/integration-with-existing-apps
)

It crashes on ` [TrustKit initSharedInstanceWithConfiguration:_trustKitConfig];`
<img width="1169" alt="screen shot 2018-07-26 at 18 40 16" src="https://user-images.githubusercontent.com/1270050/43278564-6325e5d6-9103-11e8-90df-ab13d7382069.png">

Any ideas? Has anyone got TrustKit working with RN?

**Comment by nabla-c0d3** [comment]
Hello,
on our side, we have not tried to use TrustKit in a React app. The location of the crash is surprising but I don't know much about React either.

**Comment by soumyamishra89** [comment]
I am having the same issue. any solution for this yet?

**Comment by juhasuni** [comment]
Please take a closer look at the logs, at least in my case it says:

> Terminating app due to uncaught exception 'TrustKit configuration invalid', reason: 'TrustKit was initialized with less than 2 pins...

And it crashes exactly as @apski describes above. Adding another public key hash fixed the issue.
