### ISSUE TITLE
iOS 12 Release

### ISSUE THREAD

**Issue by Awalz** [datatheorem/TrustKit#178]
Are there plans for a new release to release the iOS 12 fixes [merged in June](https://github.com/datatheorem/TrustKit/commit/057c7e13760742f4f39316df10ddea3c2ee3580b). iOS 12 GM should be out within the next two days

**Comment by JesseScott** [comment]
any update on this ?

**Comment by nabla-c0d3** [comment]
Yes, we will do a release later this month - sorry for the delay.

**Comment by JesseScott** [comment]
Okay, thanks for the update.
Do you have any rough specifics on the date and the final expected functionality?

**Comment by nabla-c0d3** [comment]
I just released 1.6.0. Thanks for your patience!
