### ISSUE TITLE
Invalid Domain 

### ISSUE THREAD

**Issue by Rustemeyerm** [datatheorem/TrustKit#179]
I'm trying to load my config file for TrustKit with an internal domain that ends in .qa, for internal testing purposes. However it keeps throwing "Terminating app due to uncaught exception 'TrustKit configuration invalid', reason: 'TrustKit was initialized with an invalid domain **MYDOMAIN.qa**"

**Comment by nabla-c0d3** [comment]
Hello,
Domains that are not using a public TLD (https://wiki.mozilla.org/Public_Suffix_List) are not supported.

**Comment by g00nix** [comment]
Have there been any changes on this? Usually when using an in-house CA you also want to pick your own domain names for the servers.
