### ISSUE TITLE
Trustkit 1.6.0 ts.ios.deployment_target = '10.0' really necessary ? 

### ISSUE THREAD

**Issue by adderly** [datatheorem/TrustKit#181]
Hello all,

Documentation is a little ambiguos, or outdated; in the Readme.md it says "..makes it easy to deploy SSL public key pinning and reporting in any iOS 8+.." .

And the .podspect says that it targets 10.0, i know all devices that support 8+ can be upgraded to 10.0 but project specifics are mostly deployed with 8+.

I think it can cleanly target 8+ without many inconveniences.

**Comment by nabla-c0d3** [comment]
I've updated the README; iOS 10+ is required (see #111).
Thanks!
