### ISSUE TITLE
Crash in getAsn1HeaderBytes

### ISSUE THREAD

**Issue by Dimple-R** [datatheorem/TrustKit#183]
Hi,

Thanks for the nice framework developed.

We are using this framework in our application which is causing crash due to exceptions not handled in the below methods.

File name: TSKSPKIHashCache.m
getAsn1HeaderBytes(NSString *publicKeyType, NSNumber *publicKeySize)
getAsn1HeaderSize(NSString *publicKeyType, NSNumber *publicKeySize)

Could you please fix this issue.

Thanks,
Dimple

**Comment by nabla-c0d3** [comment]
Hello,
What is the hostname or certificate that is causing this crash?
