### ISSUE TITLE
iOS - Different Static NSString... it's a bug?????

### ISSUE THREAD

**Issue by CodeTeamLabs** [datatheorem/TrustKit#185]
In the example project for iOS show when a pin is updated or not .. I replaced the keys to https://www.yahoo.com with valid keys and everything works but I wanted to ask a question.

In the `ViewController.m `file we have:

**static NSString * const baseURLYahoo = @ "https://www.yahoo.com/"**

this is the fact to specify the address on which to put the keys if the keys are wrong, the connection is interrupted .. I tried to keep the valid keys of yahoo and change the static string in:

**static NSString * const baseURLYahoo = @ "https://www.google.com/";**

Apparently the alert that warns us if the connection has been interrupted or not communicates us:
**"Pinning Validation succeded for https://www.google.com/**

Now I do not know if it is my mistake of interpretation or if there is actually a bug in this because changing the domain yahoo -> google I should not be able to continue with the connection using the yahoo keys ... right?

However, the NSLog report tells us that the domain has no pin on it.
**TrustKit Log : Domain www.yahoo.com is not pinned
TrustKit Log : Domain it.yahoo.com is not pinned**

**Comment by nabla-c0d3** [comment]
I’m not sure I understand the question but if you change the URL in the view controller you also need to update the configuration in the Info.plist.
