### ISSUE TITLE
undefined symbol for architecture arm 64

### ISSUE THREAD

**Issue by ekapradityagk** [datatheorem/TrustKit#190]
Hi,

i just test the framework in my apps,, but i got this error message saying undefined symbol for architecture arm 64, i google for a while, and also look in the demo you provide, you also add linker flag in "other linker flag" in build setting, but it generate another error, can you help me? 

here is the screenshot before i add other linker flag

![screen shot 2018-12-05 at 09 02 26](https://user-images.githubusercontent.com/6790426/49485308-0d1e1880-f86d-11e8-96ba-1968926e47a0.png)
![screen shot 2018-12-05 at 09 02 32](https://user-images.githubusercontent.com/6790426/49485310-0db6af00-f86d-11e8-9a18-5f31c55f82c8.png)

and here is after

![screen shot 2018-12-05 at 09 01 53](https://user-images.githubusercontent.com/6790426/49485319-19a27100-f86d-11e8-8b05-f1783f7cd202.png)

hope you can help me with this issue, 

best regards.
Eka

**Comment by ekapradityagk** [comment]
and where i can get this file? i try to add in link binary but i cant find the file
![screen shot 2018-12-05 at 09 56 44](https://user-images.githubusercontent.com/6790426/49487259-2e363780-f874-11e8-92d8-c6427b661b8e.png)

**Comment by nabla-c0d3** [comment]
Hello, 
This seems to be a problem with your environment - not sure what the error is.
