### ISSUE TITLE
Improving "Always start with pinning enforcement disabled" documentation section

### ISSUE THREAD

**Issue by flexaddicted** [datatheorem/TrustKit#192]
Reading the documentation for **Always start with pinning enforcement disabled** section I cannot understand why I need to set `kTSKEnforcePinning` to `NO`.

Based on the source code, I see that the trust decision is marked as allowed when the previous flag is set to `NO`:

```
if (validationResult == TSKTrustEvaluationFailedNoMatchingPin)
{
    // Is pinning enforced?
    if ([domainConfig[kTSKEnforcePinning] boolValue] == YES)
    {
        // Yes - Block the connection
        finalTrustDecision = TSKTrustDecisionShouldBlockConnection;
    }
    else
    {
        finalTrustDecision = TSKTrustDecisionShouldAllowConnection;
    }
}
```

Based on this, why should I set that value as written in the documentation? Should I change it after? Setting to `NO` means not taking into account the pinning. Or am I missing something?

Thanks, Lorenzo

**Comment by nabla-c0d3** [comment]
This sections says the following: "To avoid locking out too many users from your App when deploying SSL pinning for the first time". It's to avoid making a big mistake with your pinning configuration that bricks your app.
