### ISSUE TITLE
Multiple certificates for a single link

### ISSUE THREAD

**Issue by fawad-khalil** [datatheorem/TrustKit#193]
Hi, I am required to request an HTTPS link using my iOS app. I have them in .pem format and .crt format. I obtained the hash using get_pin_from_certificate.py script.

The problem is, the HTTPS link requires all three certificates, Issuing, intermediate and root, but the examples demonstrated only one hash. I have tried adding all three hashes in the array `kTSKPublicKeyHashes` but failed to request. How can I achieve results with the desired scenario? Please help I need it urgently.

**Comment by hollanderbart** [comment]
Try adding logs to TrustKit to see what's going on.

```
        TrustKit.setLoggerBlock { (message) in
            print("TrustKit log: \(message)")
        }
```
