### ISSUE TITLE
Backup Pin requirement

### ISSUE THREAD

**Issue by fawad-khalil** [datatheorem/TrustKit#194]
I would  like to know, is backup pin required necessarily to successfully request the HTTPS or providing a dummy pin like "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=" will work fine?

**Comment by nabla-c0d3** [comment]
This is explained at https://github.com/datatheorem/TrustKit/blob/master/docs/getting-started.md#always-provide-at-least-one-backup-pin
