### ISSUE TITLE
Not enough clarity around kTSKIncludeSubdomains 

### ISSUE THREAD

**Issue by myie-vvashisht** [datatheorem/TrustKit#197]
Hi, 
I have been through the documentation but couldn't get enough clarity on what and how kTSKIncludeSubdomains flag works. 
The context is that I want to change the CA for the certificate whilst keeping the pinning information and hence the hash the same so that I do not have to update the config in my mobile app and publish a new version.

**Comment by nabla-c0d3** [comment]
kTSKIncludeSubdomains is to allow subdomain.domain.com to use the pinning configuration that was set for domain.com in TrustKit. I don't think it is related to what you are trying to do.
