### ISSUE TITLE
Get TrustKit configuration invalid error for domain *.azurewebsites.net

### ISSUE THREAD

**Issue by changLiuUNSW** [datatheorem/TrustKit#199]
I try to setup trust kit for my azure websites ```*.azurewebsites.net``` and I put
TSKPinnedDomains  = azurewebsites.net
TSKIncludeSubdomains = true

When I run the application, I got exceptions says "TrustKit configuration invalid".

I see below comment in the code:
```
 // Prevent pinning on *.com
 // Ran into this issue with *.appspot.com which is part of the public suffix list
```
Does it mean ```azurewebsites.net``` is part of the public suffix list?

**Comment by nabla-c0d3** [comment]
Yes it is, so you should not be able to pin *.azurewebsites.net by design.
