### ISSUE TITLE
TrustKit Demo on iOS 12 is always 999 (valid pinning option)

### ISSUE THREAD

**Issue by liuxuan30** [datatheorem/TrustKit#201]
Hi there,

TrustKit Demo on iOS 12 is always 999 (valid pinning option). I'm not sure if this is because of the website or the old 999 issue you mentioned several times (iOS issue)

**Comment by nabla-c0d3** [comment]
Hi,
Yes, the demo app does need to be updated; the server's certificate probably changed since its last update.
