### ISSUE TITLE
SSL Pinning in react native 0.59

### ISSUE THREAD

**Issue by SunilPandey-** [datatheorem/TrustKit#204]
Hi,

a) when I pass kTSKSwizzleNetworkDelegates: or kTSKEnforcePinning as NO, then I am able to login to my app even though i pass wrong Public keys inside kTSKPublicKeyHashes.
My understanding is if i pass wrong public keys then URL should throw error.

b) When I pass  kTSKSwizzleNetworkDelegates: or kTSKEnforcePinning as YES then even i pass correct public keys inside kTSKPublicKeyHashes.  I am unable to login in app. it throws TRUSTKit validation error.

Could you please guide me, how to fix it.

**Comment by nabla-c0d3** [comment]
React native is not officially supported. Good luck!
