### ISSUE TITLE
Dependency Versions

### ISSUE THREAD

**Issue by AbhimanyuAHegde** [datatheorem/TrustKit#21]
Hi,

We are trying to use TrustKit 1.1.3 and since this Open source and there 2 dependencies(fishhook and domain_registery).
Could I get the versions of the dependencies?(fishhook and domain_registery).

Thanks in advance

**Comment by nabla-c0d3** [comment]
Hi,

Both dependencies don't seem to have version numbers:
* Fishhook: https://github.com/facebook/fishhook
* Domain registry provider: https://github.com/nabla-c0d3/domain-registry-provider

Also, for iOS 9 support, we will most likely start using RSSwizzle 0.1.0 as well (https://github.com/rabovik/RSSwizzle).
