### ISSUE TITLE
Handling a revoked certificate

### ISSUE THREAD

**Issue by richardtop** [datatheorem/TrustKit#217]
1. Does the TrustKit recognize and handle the revoked certificate?
2. If "yes", how does that logic is implemented?

I was not able to find anything about handling a revoked certificate in the TrustKIt docs, the most detailed source I was able to discover is [this stackoverflow answer](https://stackoverflow.com/questions/58227552/how-to-get-crl-and-oscp-checking-to-work-on-ios), and apparently, iOS doesn't deny a connection if it can't communicate with the OCSP provider.

If that's true, is it possible to configure the TrustKit to check against the certificate revocation and deny the connection if such check couldn't be performed?

I was able to find an evidence of TrustKit delegating the revocation check to the operating system [(code)](https://github.com/datatheorem/TrustKit/blob/master/TrustKit/Pinning/ssl_pin_verifier.m#L31), but unsure how it would behave in practice.

**Comment by nabla-c0d3** [comment]
Yes revocation checking (and most of the steps within "regular" certificate validation) is delegated to the OS; TrustKit does not do anything extra and it would be beyond its scope to provide settings for revocation checking. Good luck!
