### ISSUE TITLE
Handshaking is still happening after TrustKit implementation 

### ISSUE THREAD

**Issue by ankurpachauri88** [datatheorem/TrustKit#221]
I'm using Charles to validate the TrustKit implementation for public key pinning. When I'm doing SSL proxying through Charles, Trustkit showing the pinningNotMatched, which is fine, but Charles showing that handshaking is happening with server and network call headers are showing.

**Comment by satputepritamcts** [comment]
I am facing the issue with charles, with correct keys charles is not working
do you face same one?
