### ISSUE TITLE
No strict pinning in provided sample?

### ISSUE THREAD

**Issue by noxo** [datatheorem/TrustKit#225]
The provided sample passes in NSURLSessionAuthChallengePerformDefaultHandling into callback, if the pinning fails:

```
- (void)URLSession:(NSURLSession *)session 
              task:(NSURLSessionTask *)task 
didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge 
 completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler {
{
    TSKPinningValidator *pinningValidator = [[TrustKit sharedInstance] pinningValidator];
    // Pass the authentication challenge to the validator; if the validation fails, the connection will be blocked
    if (![pinningValidator handleChallenge:challenge completionHandler:completionHandler])
    {
        // TrustKit did not handle this challenge: perhaps it was not for server trust
        // or the domain was not pinned. Fall back to the default behavior
        completionHandler(NSURLSessionAuthChallengePerformDefaultHandling, nil);
    }
}
```
Shouldn't it use NSURLSessionAuthChallengeCancelAuthenticationChallenge instead here, which would result in closing of connection when pinning fails? Doesn't NSURLSessionAuthChallengePerformDefaultHandling result in letting OS performing the certificate check instead? Why example is written like this, as developers requirement is most likely to implement strict pinning to certain certificates?

**Comment by nabla-c0d3** [comment]
`[TSKPinningValidator handleChallenge:completionHandler:]` will return false only if it did not handle the challenge, leaving the OS to handle it. If pinnning validation failed it already handled it (https://github.com/datatheorem/TrustKit/blob/master/TrustKit/TSKPinningValidator.m#L219) and will return true here.

**Comment by noxo** [comment]
Thanks for clarification! TSKPinningValidator.handleChallenge() returning "false" basically indicates that "authenticationMethod"/challenge is something that TrustKit does not support, e.g NTLM authentication (NSURLAuthenticationMethodNTLM).

**Comment by nabla-c0d3** [comment]
More specifically it indicates that TrustKit did not handle the challenge, which could be due tovarious reasons as visible in the code I linked, including a non-supported challenge (but there are other reasons too).
