### ISSUE TITLE
Unable to pin to Amazon AWS domain: invalid domain error

### ISSUE THREAD

**Issue by gadget-man** [datatheorem/TrustKit#226]
I'm trying to setup pinning to amazonaws.com for my AWS configuration. However the app immediately crashes with the following error:
`'TrustKit was initialized with an invalid domain amazonaws.com'`

Changing the domain to `google.com` allows the script to proceed.

**Comment by nabla-c0d3** [comment]
By design, TrustKit will crash when trying to configure a domain that's on the public suffix list (ie. a domain that you definitely don't own):  https://publicsuffix.org/

**Comment by gadget-man** [comment]
So TrustKit can’t be used for certificate pinning to my AWS endpoint?  Seems a fairly significant limitation, unless I’m missing something.

**Comment by gadget-man** [comment]
And why does it allow pinning to google.com, which I definitely don’t own?

**Comment by nabla-c0d3** [comment]
You can pin to an AWS endpoint by setting up your own/custom domain to point to it, with a certificate that you control (a prerequisite for pinning).

**Comment by gadget-man** [comment]
> You can pin to an AWS endpoint by setting up your own/custom domain to point to it, with a certificate that you control (a prerequisite for pinning).

I’m trying to avoid this step as it wasn’t necessary in order to implement certificate pinning on Android. I also don’t understand why it works fine if trying to pin to www.google.com (or yahoo.com as shown in the code example), if by design it’s only supposed to work with domains I own

**Comment by nabla-c0d3** [comment]
We can't really know for all domains whether you own them or not (such as google.com), but any domain on the public suffix list is definitely not one that you own, hence the crash. 

If you pin amazonaws.com in your app, how will you know when you need to update the pinning configuration and release a new version of your app? How will you manage certificate rotation or any change in the server's certificate chain? You can't and will only discover such changes after they happened (which will cause your app to stop working).
