### ISSUE TITLE
TSKTrustEvaluationFailedInvalidCertificateChain

### ISSUE THREAD

**Issue by juppjupp** [datatheorem/TrustKit#227]
Connection get refused with error "TSKTrustEvaluationFailedInvalidCertificateChain". We are using the same hashkeys as in our Android implementation where everything seems to work. Any suggestion why this error occur on iOS?

**Comment by nabla-c0d3** [comment]
TSKTrustEvaluationFailedInvalidCertificateChain means that the default validation done by iOS is failing (ie. not TrustKit's additional pinning validation). I would look at the server's certificate chain and make sure an iOS device is able to connect to it via Safari; perhaps the app's transport security policy needs to be updated.
