### ISSUE TITLE
Invalid value for TSKPublicKeyAlgorithms

### ISSUE THREAD

**Issue by sakthia01** [datatheorem/TrustKit#231]
Hi Team,

When I try to run the demo project that in github, I am facing the below issue.

Terminating app due to uncaught exception 'TrustKit configuration invalid', reason: 'TrustKit was initialized with an invalid value for TSKPublicKeyAlgorithms for domain www.datatheorem.com'.

Please let me know how can I proceed.

**Comment by nabla-c0d3** [comment]
Hello,
I just tried run the demo applications in https://github.com/datatheorem/TrustKit/tree/master/TrustKitDemo and they worked fine; perhaps you modified the TrustKit configuration?
