### ISSUE TITLE
Bump OS support versions in September

### ISSUE THREAD

**Issue by adamkaplan** [datatheorem/TrustKit#232]
As iOS 14 is being released in several weeks, it would be nice to bump minimum support from the iOS 10 generation to the iOS 11 generation (+tv, watch, mac). This would maintain N-3 major OS version support (iOS 11, 12, 13, 14).

The main benefit of this change would be removal of the two insecure coding branches:
https://github.com/datatheorem/TrustKit/blob/master/TrustKit/Pinning/TSKSPKIHashCache.m#L201
https://github.com/datatheorem/TrustKit/blob/master/TrustKit/Pinning/TSKSPKIHashCache.m#L226

Which are periodically flagged by Yahoo security (even though we don't support iOS 10, we're 12+).

**Comment by nabla-c0d3** [comment]
Yeah, agreed and thanks for the notice!

**Comment by nabla-c0d3** [comment]
Released as v1.7.0.
