### ISSUE TITLE
SSL pinning not working on the Webview request domain

### ISSUE THREAD

**Issue by RajeshCentrica** [datatheorem/TrustKit#238]
Hi,

When loading the request URL on the UIWebview and do intercept the request URL using  Charles we can see the all the request and response. 
Does TrustKit support Webview SSL pinning?

SDK TrustKit version 1.6.5 
We are passing the valid kTSKPublicKeyHashes.

Sample code snippet

```
        let trustKitConfig = [
            kTSKSwizzleNetworkDelegates: true,
            kTSKPinnedDomains: [
                “www.requestdomain.com”: [
                    kTSKIncludeSubdomains : true,
                    kTSKPublicKeyAlgorithms: [kTSKAlgorithmRsa2048],
                    kTSKPublicKeyHashes: [
                        “HashKey1”,
                        "HashKey2”
                    ],]]] as [String : Any]
        TrustKit.initialize(withConfiguration: trustKitConfig)

````

Please assist on this issue.

**Comment by nabla-c0d3** [comment]
Hello,
Trustkit does not support UIWebView,, but it does support WKWebView (https://developer.apple.com/documentation/webkit/wkwebview?language=objc).

**Comment by RajeshCentrica** [comment]
Hi @nabla-c0d3 

Thanks for details.

We used WKWebView only but it is in the react-native library 

We load the URL on WKWebView but TrustKit used from Native side. SSL pinning happened API domain request(API layer managed from React native side).

The SSL pinning not happened  WKWebView URL request.

Please let me know if any changes need to be done from the Native side?

**Comment by dipendra-sharma** [comment]
@nabla-c0d3 Any help on this? 

`We load the URL on WKWebView but TrustKit used from Native side. SSL pinning happened API domain request(API layer managed from React native side).`
