### ISSUE TITLE
 Crashlytics: ssl_pin_verifier.m line 43

### ISSUE THREAD

**Issue by siddew201** [datatheorem/TrustKit#283]
Crashed: com.apple.main-thread
0  TCPApp                         0x537e48 AccountListViewController.disableInteractionForConsentSwitch() + 4374543944
1  TCPApp                         0x539040 partial apply for specialized closure #1 in AccountListViewController.toggleConsent(of:) + 355 (AccountListViewController.swift:355)
2  TCPApp                         0x40b644 thunk for @escaping @callee_guaranteed (@guaranteed Result<ConsentUpdateModel, NetworkError>) -> () + 4373313092 (<compiler-generated>:4373313092)
3  TCPFoundationKit               0x4329c closure #6 in closure #1 in ServiceManager.getCoreURLSessionTask<A>(request:tokenRefreshed:completion:) + 225 (ServiceManager.swift:225)
4  TCPFoundationKit               0xa8c0 thunk for @escaping @callee_guaranteed () -> () + 4498221248 (<compiler-generated>:4498221248)
5  libdispatch.dylib              0x1e68 _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
7  libdispatch.dylib              0x11f48 _dispatch_main_queue_drain + 928
8  libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF + 44
9  CoreFoundation                 0x522f0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
10 CoreFoundation                 0xc1f4 __CFRunLoopRun + 2532
11 CoreFoundation                 0x1f6b8 CFRunLoopRunSpecific + 600
12 GraphicsServices               0x1374 GSEventRunModal + 164
13 UIKitCore                      0x513e88 -[UIApplication _run] + 1100
14 UIKitCore                      0x2955ec UIApplicationMain + 364
15 TCPApp                         0xa2d2f0 main + 39 (AppDelegate.swift:39)
16 ???                            0x106679ce4 (Missing)

**Comment by EthanArbuckle** [comment]
None of the frames in the provided stacktrace include TrustKit. Where do you see that ssl_pin_verifier is responsible for the crash?
