### ISSUE TITLE
No visible @interface for 'TSKSPKIHashCache' declares the selector 'getPublicKeyDataFromCertificate_legacy_ios:'

### ISSUE THREAD

**Issue by rad-chomik** [datatheorem/TrustKit#288]
Hi Team

After updating the deployment target of our app to 11.0 I am getting that kind of error, see the image attached 

<img width="1085" alt="Screenshot 2022-11-10 at 10 59 18 am" src="https://user-images.githubusercontent.com/91895133/201076043-7a2824b0-6a95-4dd4-9320-82a79f02faf3.png">

This error happens only in this one line that function does not throw errors in other lines( as you can see on the image it is called in two more places but causing error just in this one)

I'm on Monterey 12.6 macOS using Xcode Version 14.0.1 (14A400)

Any suggestions on how can I fix this?

Kindest regards
Rad

**Comment by EthanArbuckle** [comment]
You appear to be running an old version of the SDK. Can you try updating to the latest release?

**Comment by touchyvivace** [comment]
i've faced the same issues did you solved ? @rad-chomik
