### ISSUE TITLE
[Question] Can I use this to trust a self-signed cert?

### ISSUE THREAD

**Issue by matallui** [datatheorem/TrustKit#291]
Hi! I have this Expo app that needs to talk to random API servers that don't have a FQDN and use a self-signed certificate.
All of them use the same self-signed certificate, so I'm assuming there's a way for us to add the cert to the trusted list of certs and have all our requests (we need to use `fetch` and `Websocket`) go through just fine.

Will this project fit those needs?

I think I found a solution for Android [here](https://stackoverflow.com/questions/55372642/how-to-add-network-security-config-xml-to-manifest-in-expo-app-without-ejecting/70775576#70775576) (I have yet to test it), but need to find a similar solution for iOS.

Thanks in advance!

**Comment by nabla-c0d3** [comment]
Hello!
Unfortunately self-signed certificates are not supported by TrustKit. Good luck!
