### ISSUE TITLE
Support for iOS 12 & 13 needed

### ISSUE THREAD

**Issue by JuhaO81** [datatheorem/TrustKit#295]
We have tens of thousands customers using iOS 12 & 13 so we cannot drop the support for them. Also we are banking app so we must keep our libraries running on recent versions. Especially all libraries releated to security like this one here.

**Comment by pawisoon** [comment]
@JuhaO81  Release 3.0.1 brought back support for iOS 12+ :)

**Comment by JuhaO81** [comment]
Really nice and thanks! Trusting it works and closing this ticket now :)
