### ISSUE TITLE
Trustkit not building on Xcode 14.3

### ISSUE THREAD

**Issue by Sjenk** [datatheorem/TrustKit#298]
Starting from xcode 14.3 building trustkit produces the following issue:
 "A function declaration without a prototype is deprecated in all versions of C"
The solution seems to be adding void to the following functions
```NSURLSessionConfiguration *ephemeralNSURLSessionConfiguration() {``` in configuration_utils at line 102
and to
``` static NSMutableDictionary *swizzledClassesDictionary(void){ ```
In RSSWizzle line 270

**Comment by pawisoon** [comment]
I confirm this fixes the build of the project

**Comment by aj-dt** [comment]
This is now live in v3.0.2. Closing as fixed.
