### ISSUE TITLE
IOS17 support Trust Kit Crash (iphone15 physical)

### ISSUE THREAD

**Issue by LeoAnt02** [datatheorem/TrustKit#314]
Currently the ssl-pining cause a crash on new iPhones 15 Pro physical devices
I tried on simulator iphone 15 and Iphone 15 Pro- ios 17.0.0 - and there is no issues

This is breaking production devices also

Target Device :
**Iphone 15 Pro (Physical)
IOS v17.0.2
Xcode 15**

There is no error in console, will have to debug further and edit this post
But this is where Xcode crash in screenshot below

Issue seems to come from TrustKit need a little update with version 17.0.2 (iphone15)

![image](https://github.com/datatheorem/TrustKit/assets/21208398/33c97db7-07d4-438e-9f79-af4e4171cdfe)

_Something I've noticed that may cause an issue, is that iphone15 Pro (physical), is read as an Iphone16 in singature binaries, I believe this is a mistake from apple, not sure if this affect TrustKit or SSL pining but worth to mention it_

**Comment by HakanSAYAR** [comment]
I've faced the same issues. Any solution?

**Comment by LeoAnt02** [comment]
@HakanSAYAR 
I've successfully solved the issue  by Updating spec repo `cocoapods` on ios for TrustKit 3.0.3 (was using 3.0.2)

```
pod repo update
pod install
```

Then trustkit was updated to 3.0.3 and everything works now 

#309
