### ISSUE TITLE
_SecTrustCopyCertificateChain getting EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by aymather** [datatheorem/TrustKit#317]
<img width="1156" alt="Screenshot 2023-10-17 at 4 13 15 PM" src="https://github.com/datatheorem/TrustKit/assets/41848756/0726f429-3b59-4233-9d7c-508ae3a22b6d">

Trustkit@3.0.2
XCode@15.0

I've been using TrustKit for over a year on this project and I only started noticing this issue when i updated xcode. Don't have much more information than that right now tbh

**Comment by HLeshan** [comment]
Getting same error after updating xCode

**Comment by lorenzoangelini** [comment]
Hi! i had the same problem. 
To resolve i installed the version 3.0.3 into pod file
 pod 'TrustKit','3.0.3'

**Comment by EthanArbuckle** [comment]
Fixed in v3.0.3 https://github.com/datatheorem/TrustKit/commit/11da1c781e168732e6b7d1480b4615dceac44af4
