### ISSUE TITLE
Link warnings 

### ISSUE THREAD

**Issue by aviv-zent** [datatheorem/TrustKit#34]
I am building an ios target with "Deployment Target" = 8.1
I am using Trust kit as a pod (pod 'TrustKit') and I see the following link warnings:
(null): Object file (/Users/X/Documents/Projects/Y/Pods/TrustKit/TrustKit/Dependencies/domain_registry/ios/libassert_lib.a(assert.o)) was built for newer iOS version (9.0) than being linked (8.1)
(null): Object file (/Users/X/Documents/Projects/Y/Pods/TrustKit/TrustKit/Dependencies/domain_registry/ios/libdomain_registry_lib.a(registry_search.o)) was built for newer iOS version (9.0) than being linked (8.1)
(null): Object file (/Users/X/Documents/Projects/Y/Pods/TrustKit/TrustKit/Dependencies/domain_registry/ios/libdomain_registry_lib.a(trie_search.o)) was built for newer iOS version (9.0) than being linked (8.1)
(null): Object file (/Users/X/Documents/Projects/Y/Pods/TrustKit/TrustKit/Dependencies/domain_registry/ios/libinit_registry_tables_lib.a(init_registry_tables.o)) was built for newer iOS version (9.0) than being linked (8.1)

**Comment by nabla-c0d3** [comment]
Hello,
TrustKit links a few pre-compiled static libraries which were built with a newer version of the SDK than the one you are using. This is a harmless warning (http://stackoverflow.com/questions/31843900/xcode-7-warnings-object-file-was-built-for-newer-ios-version-than-being-linked) as these libraries do not use any iOS APIs.
In the next release tho, I will re-build them with a lower deployment target so these warnings go away.
Thanks!
