### ISSUE TITLE
Scripts generate different pins.

### ISSUE THREAD

**Issue by onato** [datatheorem/TrustKit#35]
I tried following to generate a pin but only the second method gave me a pin that worked:

`./get_pin_from_server.sh tribesocial.com` 

and

```
openssl x509 -inform der -in ~/Downloads/tribesocial.com.cer -out tribesocial.com.pem
./get_pin_from_pem_certificate.sh tribesocial.com.pem
```

**Comment by nabla-c0d3** [comment]
Hi, I tried the first command and it seemed to work fine. 
What issue did you run into? FYI the second command will pin the leaf certificate's key; when deploying pinning, it is easier to start with the CA certificate key (which is a lot less likely to change).

**Comment by onato** [comment]
It returns me a pin but when I use this in the app it fails pin validation.

**Comment by nabla-c0d3** [comment]
I just had a quick look. Your server seems to be misconfigured in two different ways:

* It is returning the anchor certificate (see the certification paths here https://www.ssllabs.com/ssltest/analyze.html?d=tribesocial.com&hideResults=on); ssl servers should only return the leaf and all the intermediate certificates, but not the CA cert.
* There seems to be multiple valid trust paths; the one used by iOS is not the one "seen" by the script (which receives an additional CA certificate). Hence the pin the script returns is for "Daddy Class 2 Certification Authority" but the path validation on iOS successfully ends at "Go Daddy Root Certificate Authority - G2". Not sure why you have multiple validation paths; perhaps to support older devices ?

Regardless, you should always pin the highest/CA certificate within the chain seen by iOS. For tribesocial.com it is the "Go Daddy Root Certificate Authority - G2" certificate, which has the following pin:

    "Ko8tivDrEjiY90yGasP6ZpBU4jwXvHqVvQI0GS3GNdA="
