### ISSUE TITLE
Crashing the App when a proxy is used. 

### ISSUE THREAD

**Issue by developer1234567** [datatheorem/TrustKit#36]
I would like to crash my App when a proxy is used. Is this possible with TrustKit?

**Comment by nabla-c0d3** [comment]
You could use TrustKit to pin your server's public key and then detect if the public key your App received is not the right one (meaning something, perhaps a proxy, is intercepting the App's traffic). 
What are you trying to do specifically ? 
If the goal is to prevent someone from doing reverse-engineering on your App or inspecting its traffic, crashing the App can still be trivially bypassed.
