### ISSUE TITLE
Disabling log for normal operation

### ISSUE THREAD

**Issue by nickdnk** [datatheorem/TrustKit#37]
Hello. Great kit, love the simplicity.

But, is there a way we could introduce an on/off option for the default logging? I use it in apps while developing them, and it takes up quite a lot of space in the system log, which is not really necessary when nothing is wrong and you're not debugging anything. An option to turn this off would be great.

I'd PR it if I had any clue how to properly implement such an option without breaking anything.

Edit: Looked at the source. Seems it only logs in Debug mode. I don't know if this is me doing something wrong or if this is intended behavior.

**Comment by nabla-c0d3** [comment]
Hello,
Yeah this is intended behavior: logging is only enabled when building for Debug. This was done to avoid having a switch that developers might forget about, thereby enabling logging in their Release builds. For your use case, this should be fine as well ?

**Comment by nickdnk** [comment]
Hey

If I had any clue where to change or differentiate between debug and release, then yes. I've never had to change this for any other frameworks (or reasons at all), so I was honestly not aware. I realize this may come of as extremely ignorant.

I guess I'll just have to look into that. You learn something every day.

**Comment by nabla-c0d3** [comment]
Sounds good. When you "Archive" your App in Xcode, it builds it for Release (thereby disabling the TrustKit logs). If it's still a problem, please re-open this issue.

**Comment by MaximusMcCann** [comment]
Would still like the ability in Debug mode to disable the logs.  I have a pull request here that uses a launch argument: https://github.com/datatheorem/TrustKit/pull/61
