### ISSUE TITLE
Leverage iOS 10 APIs to simplify SPKI generation

### ISSUE THREAD

**Issue by nabla-c0d3** [datatheorem/TrustKit#51]
iOS 10 has some useful new APIs:
1. It is possible to directly extract the public key bytes using `SecKeyCopyExternalRepresentation()`. Using this API, TrustKit would no longer need to leverage the Keychain in order to get the public key bytes.
2. It is possible to identify the type of public key using `SecKeyCopyAttributes()`, thereby removing the need for the developer to specify the key algorithm in the TrustKit policy.

**Comment by ppaulojr** [comment]
Without this PR we are getting:
```
TrustKit: Error - could not generate the SPKI hash for 
```

**Comment by nabla-c0d3** [comment]
It can happen sometimes, but it should be a rare occurence. This error is caused by random Keychain failures that may happen once in a while and that are very difficult to reproduce (basically a bug in iOS). As you mentioned, this error won't happen on iOS 10 since we don't leverage the Keychain on iOS 10 devices.

**Comment by ppaulojr** [comment]
It's happening on iOS10.

I could fix it by adding this entitlement
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>keychain-access-groups</key>
	<array>
		<string>$(AppIdentifierPrefix)com.cipherhealth.ourAPP</string>
	</array>
</dict>
</plist>
```

**Comment by nabla-c0d3** [comment]
What is your Base SDK and which version of TrustKit are you using?

**Comment by ppaulojr** [comment]
Base SDK: 10.0
TrustKit: 
  - TrustKit (1.3.2)

**Comment by nabla-c0d3** [comment]
Ok yeah, this will not happen with TrustKit 1.4.0 (to be released when CocoaPods fixes their support for Xcode 8) because it will no longer use the Keychain on iOS 10 devices.

Still, any idea why your App did not have Keychain access to begin with? Did you tweak the default entitlements?

**Comment by ppaulojr** [comment]
I didn't tweet the entitlements, not sure either.

**Comment by adamkaplan** [comment]
@nabla-c0d3 This still open? 1.4 and Xcode 8 support are both done ✅

**Comment by nabla-c0d3** [comment]
The first bulletpoint (extracting the SPKI) was done, but not the second one; I created a separate task for it: #111 .
