### ISSUE TITLE
Feature request: debug message level configuration

### ISSUE THREAD

**Issue by dmi3j** [datatheorem/TrustKit#52]
Would be nice to have some control over console messages from TrustKit. Now it's only check for DEBUG. But some configurable property is highly appreciated.

**Comment by nabla-c0d3** [comment]
Hi,
Do you have a specific idea of the specific things you'd like to be able to configure? Just an on/off setting or more?
Thanks!

**Comment by dmi3j** [comment]
Just and on/off switch for now.
