### ISSUE TITLE
Pinning is not working in some webservices.

### ISSUE THREAD

**Issue by paritsohraval100** [datatheorem/TrustKit#54]
Hi, It's a really good library and specially it is very easy to implement in our code.

I have a query. I implemented it in my app and then tried to trash network traffic by Charles.  Now according to pinning it should not be trash. But i am able to trash some webservices. 

I am not able to trash 2-3 webservices but rest i can trash by Charles. I am using ASIHTTP library. I am not sure will it vary on different webservices ?

**Comment by nabla-c0d3** [comment]
Hello,
Unfortunately we do not support the ASIHTTP library as it has not been updated in five years; the developer page explicitly states that developers should stop using it. Hence I do not know what works and what doesn't work when using it with TrustKit.
Good luck!
