### ISSUE TITLE
Xcode 6.4 build failed: Parser issue

### ISSUE THREAD

**Issue by rcbs** [datatheorem/TrustKit#64]
Hi,

I went through the sample code base, I use pod file as dependency. I observe
In Xcode 7, TrustKit works like charm. 
In Xcode 6, Trustkit build failed with Parse issue of about 28 errors in same category.

Example:
Class name: reporting_utils.m
Issue type: Parse issue
Issue Description: Expected '>' in the below line
NSArray<NSString *> *convertTrustToPemArray(SecTrustRef serverTrust)

Since i need to support from iOS 7.1, when i try to build the application in Xcode 6.4, i got the above build failed error message.

Please advice on this to proceed further to fix the issue

**Comment by nabla-c0d3** [comment]
Xcode 6 does not support generics:

    NSArray<NSString *> *

Let me think about the right course of action here. I am guessing there is no way to compile for iOS 7 using Xcode 7?

**Comment by nabla-c0d3** [comment]
Actually I checked and you should be able to pick iOS 7 as the deployment target in newer versions of Xcode including 7. Why do you need to specifically use Xcode 6?

**Comment by rcbs** [comment]
Since customer environment, they didn't rollout for  OS update. Since XCode 7 need to upgrded from XCode 6, most of development  dependency is there. So we need to compile in XCode 6.

Is there any possible way to compile certificate pinning with XCode 6 with trustkit?

Please guide on!

**Comment by nabla-c0d3** [comment]
Sorry, we can't support older versions of Xcode; iOS 7 is still supported by TrustKit but Xcode 6 is not.
