### ISSUE TITLE
Is this vulnerable to ssl-kill-switch2 on OSX?

### ISSUE THREAD

**Issue by loco41211** [datatheorem/TrustKit#67]
Could the whole pinning process here be intercepted and manipulated using ssl-kill-switch2? 

https://github.com/nabla-c0d3/ssl-kill-switch2

Anything you guys can do to protect against that?

**Comment by nabla-c0d3** [comment]
Yes - and I'm actually the maintainer of that project so it does support disabling TrustKit :). SSL pinning (whether in TrustKit or in general) is not designed to protect an App from code running as root on the device (like kill switch) or from a user trying to reverse-engineer your App. It is purely a network protection measure, nothing more.
