### ISSUE TITLE
Support for TCP?

### ISSUE THREAD

**Issue by eladav** [datatheorem/TrustKit#76]
Hey,
In our app we use a library called [CocoaAsyncSocket](https://github.com/robbiehanson/CocoaAsyncSocket) and we want to use your library to perform certificate pinning on our TLS secured TCP connection (I couldn't find a way to properly do it in CocoaAsyncSocket's docs).
Is it possible to do that?

Thanks,
Elad

**Comment by nabla-c0d3** [comment]
Hello,
Yes it is possible:
* You need to enable and use the `socket:didReceiveTrust:completionHandler` method (https://github.com/robbiehanson/CocoaAsyncSocket/blob/master/Source/GCD/GCDAsyncSocket.h#L1206) to receive the server's `SecTrustRef` object.
* Then you can pass the trust object to `[TSKPinningValidator evaluateTrust:forHostname:]` (https://datatheorem.github.io/TrustKit/documentation/Classes/TSKPinningValidator.html#//api/name/evaluateTrust:forHostname:). Be very careful when doing so as `evaluateTrust:forHostname:` will not check the certificate at all if the domain is not pinned, and you will need to do it manually or your App will be insecure.

**Comment by eladav** [comment]
Thank you!
I'll try it out and be back with the results.

**Comment by nabla-c0d3** [comment]
Great! Let me know how it goes.

**Comment by eladav** [comment]
Worked great and was very convenient to use. Thanks for the great lib!
