### ISSUE TITLE
Manual tests for TCP certificate pinning

### ISSUE THREAD

**Issue by eladav** [datatheorem/TrustKit#78]
I used TrustKit to pin certificates to my TCP over TLS connection as described in #76 
I want to test it out.
I replaced some characters in the pinned public key and it rejected the connection, I replaced the pinned hostname and it rejected the connection. 
Now I want to do some manual security tests on the app, so I looked at [Zap](https://www.owasp.org/index.php/OWASP_Zed_Attack_Proxy_Project) but it only supports proxying http connections and I got a plain old TCP connection.
Do you know how can I do something like that?
Is there another, simpler way to get the same level of test Zap provides?
How would you go about testing something like that?

I know it's not an issue with the library, but it might be something others find useful, and may be a starting point for adding testing strategies to the documentation.

**Comment by nabla-c0d3** [comment]
Sure - last time I had to do this the tools weren't as easy to use as Zap or Fiddler. I've had success with https://github.com/nccgroup/tcpprox , but I was told that https://mitmproxy.org/ is pretty good too. Good luck and let me know if you find anything odd!

**Comment by eladav** [comment]
Thanks!
I'll try and document the complicated parts and share how it went...
