### ISSUE TITLE
App randomly crashes with Trustkit enabled

### ISSUE THREAD

**Issue by Fedenieto90** [datatheorem/TrustKit#92]
Random crashes occur in my app **only** when Trustkit is **enabled**. I think that the problem can be caused by one of the methods inside the reporting_utils.m class.

This section of the code can be the problem:

// Get the data and transfer ownership to ARC
// Explicitly calling CFRelease() at the end of this function can crash the test suite
NSData *certificateData = (NSData *)CFBridgingRelease(SecCertificateCopyData(certificate));
Add Comment

Thanks!

**Comment by nabla-c0d3** [comment]
Hello,
Thanks for the report. Do you have a stack trace? Is it something that happens every time or is random?
Thanks!

**Comment by Fedenieto90** [comment]
Hi! Sure I have the stack trace:

<img width="539" alt="screen shot 2017-02-07 at 12 20 33 pm" src="https://cloud.githubusercontent.com/assets/5543129/22703285/61a05d74-ed42-11e6-8588-6f65a916ca62.png">

It does not happen every time, it's random.

Thanks!

**Comment by nabla-c0d3** [comment]
Thanks - what is the version of IOS ? Are you using TrustKit 1.4.1 ?

**Comment by Fedenieto90** [comment]
The version of iOS is 10.2 and I'm using TrustKit 1.3.0. Should I update the version? Does it have any special updates?

**Comment by nabla-c0d3** [comment]
Ok, can you try the latest version? It might have been fixed.

**Comment by Fedenieto90** [comment]
I'll try with the latest version! Thanks!

**Comment by nabla-c0d3** [comment]
Sounds good - please reopen this if it still happens.
