### ISSUE TITLE
Fix incorrect code sample for -[TSKPinningValidator handleChallenge:completionHandler:]

### ISSUE THREAD

**Issue by kballard** [datatheorem/TrustKit#93]
The [code sample](https://datatheorem.github.io/TrustKit/documentation/Classes/TSKPinningValidator.html#/c:objc(cs)TSKPinningValidator(cm)handleChallenge:completionHandler:) for `-[TSKPinningValidator handleChallenge:completionHandler:]` in the documentation looks like

```objc
- (void)webView:(WKWebView *)webView
didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge
completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition,
NSURLCredential *credential))completionHandler
{
    if ([challenge.protectionSpace.authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust])
    {
        [TSKPinningValidator handleChallenge:challenge completionHandler:completionHandler];
    }
}
```

This sample is broken, as it does not call the completion handler if the authentication method is not `NSURLAuthenticationMethodServerTrust`.

Additionally, given that `-handleChallenge:completionHandler:` already checks the authentication method, a simpler implementation would look like

```objc
- (void)webView:(WKWebView *)webView
didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge
completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition,
NSURLCredential *credential))completionHandler
{
    if (![TSKPinningValidator handleChallenge:challenge completionHandler:completionHandler]) {
        completionHandler(NSURLSessionAuthChallengePerformDefaultHandling, nil);
    }
}
```

**Comment by nabla-c0d3** [comment]
Thanks for the feedback. Let me think about this more. I think I wrote the code sample this way to make it clear that the developer needs to act on anything that's not `NSURLAuthenticationMethodServerTrust`.

**Comment by kballard** [comment]
I would argue that anyone who wants to handle other session-level authentication challenges should be capable of modifying the sample code on their own to handle it. Also, I expect that most people don't actually want to handle other session-level authentication challenges, so the sample code should be something that they can copy & paste into their own code without problems.

**Comment by nabla-c0d3** [comment]
Yep, I agree. Thanks!
