### ISSUE TITLE
Did TrustKit use the fishhook ?

### ISSUE THREAD

**Issue by AlphaDream** [datatheorem/TrustKit#94]
I can't find any code of fishhook, but I saw that TrustKit use the fishhook from http://stackoverflow.com/questions/31649581/why-i-cant-hook-my-private-function-with-fishhook

**Comment by nabla-c0d3** [comment]
Yes, TrustKit was using fishhook initially but not anymore; details here: https://nabla-c0d3.github.io/blog/2015/10/17/trustkit-ios-9-shared-cache/

**Comment by AlphaDream** [comment]
I got it,  thank you for being so helpful!
