### ISSUE TITLE
Error message during initilization if SPKI Cache file doesn't exist

### ISSUE THREAD

**Issue by wiedem** [datatheorem/TrustKit#95]
**iOS framework TrustKit v1.4.1.**

The following error message is shown if you start an app for the first time or if the SPKI cache file doesn't exist (yet / no more): 
> *** -[NSKeyedUnarchiver initForReadingWithData:]: data is NULL

The cause for this problem is inside the [getSpkiCacheFromFileSystem](https://github.com/datatheorem/TrustKit/blob/1.4.1/TrustKit/Pinning/public_key_utils.m#L378) function:
```
NSData *serializedSpkiCache = [NSData dataWithContentsOfFile:spkiCachePath];
spkiCache = [NSKeyedUnarchiver unarchiveObjectWithData:serializedSpkiCache];
```

`dataWithContentsOfFile` will return a `nil` value if the file doesn't exist or cannot be read. This case should be handled by the function and the call to the `NSKeyedUnarchiver` should not be made.

**Comment by nabla-c0d3** [comment]
Hello,
This should only display an error in the logs, which is expected behavior, or are you getting a crash?
Thanks!

**Comment by wiedem** [comment]
> This should only display an error in the logs, which is expected behavior, or are you getting a crash?

I'm a bit confused, not handling this error is "expected behavior"? Calling `unarchiveObjectWithData:` with a `nil` parameter is an invalid call. Apple currently only shows an error message in the console logs but according to the [official documentation](https://developer.apple.com/reference/foundation/nskeyedunarchiver/1413894-unarchiveobjectwithdata?language=objc) it actually should raise an exception. Apple could change the current behavior at any point and raise an exception instead.

What's the harm in checking the value for `nil` as you should always do if you use `[NSData dataWithContentsOfFile:]`?
```
NSData *serializedSpkiCache = [NSData dataWithContentsOfFile:spkiCachePath];
if (serializedSpkiCache) {
    spkiCache = [NSKeyedUnarchiver unarchiveObjectWithData:serializedSpkiCache];
}
```

**Comment by nabla-c0d3** [comment]
The documentation is pretty clear about this (which I didn't know) so that's fair - will fix it.

**Comment by nabla-c0d3** [comment]
Looks like you already did, thanks again!

**Comment by wiedem** [comment]
> Looks like you already did, thanks again!
You're welcome :)
